import { defineConfig } from 'vitepress';

export default defineConfig({
    srcDir: 'content',
    lang: 'en-US',
    title: 'Redot Documentation',
    description:
        'Developer documentation for building Laravel admin dashboards with Redot.',
    cleanUrls: true,
    lastUpdated: true,
    head: [
        ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
        ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
        [
            'link',
            {
                rel: 'stylesheet',
                href: 'https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;1,9..40,400&family=JetBrains+Mono:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap',
            },
        ],
    ],
    vite: {
        publicDir: '../public',
    },
    themeConfig: {
        siteTitle: false,
        logo: {
            light: '/logo-light.svg',
            dark: '/logo-dark.svg',
        },
        nav: [
            { text: 'Guide', link: '/getting-started/introduction' },
            { text: 'Packages', link: '/packages/auth/overview' },
            { text: 'Frontend', link: '/frontend/asset-system' },
            { text: 'Components', link: '/components/overview' },
            { text: 'redot.dev', link: 'https://redot.dev' },
        ],
        search: { provider: 'local' },
        outline: { level: [2, 3], label: 'On This Page' },
        editLink: {
            pattern: 'https://github.com/redot-src/core/edit/master/docs/content/:path',
            text: 'Edit on GitHub',
        },
        socialLinks: [{ icon: 'github', link: 'https://github.com/redot-src/core' }],
        footer: {
            message:
                'Proprietary — for use within the Redot Dashboard. Product site: redot.dev',
            copyright: `Copyright © ${new Date().getFullYear()} Redot`,
        },
        sidebar: [
            {
                text: 'Getting Started',
                collapsed: false,
                items: [
                    { text: 'Introduction', link: '/getting-started/introduction' },
                    { text: 'Installation & Publishing', link: '/getting-started/installation' },
                    { text: 'Project Structure', link: '/getting-started/project-structure' },
                ],
            },
            {
                text: 'Architecture',
                collapsed: false,
                items: [
                    { text: 'Service Provider', link: '/architecture/service-provider' },
                    { text: 'Configuration', link: '/architecture/configuration' },
                    { text: 'Runtime & Dependencies', link: '/architecture/runtime-and-dependencies' },
                ],
            },
            {
                text: 'Foundation',
                collapsed: false,
                items: [
                    { text: 'Helpers', link: '/foundation/helpers' },
                    { text: 'Settings', link: '/foundation/settings' },
                    { text: 'Localization', link: '/foundation/localization' },
                    { text: 'Models', link: '/foundation/models' },
                    { text: 'Controllers & Responses', link: '/foundation/controllers-and-responses' },
                    { text: 'Middleware', link: '/foundation/middleware' },
                    { text: 'Casts', link: '/foundation/casts' },
                    { text: 'Validation Rules', link: '/foundation/rules' },
                    { text: 'Jobs', link: '/foundation/jobs' },
                    { text: 'Notifications', link: '/foundation/notifications' },
                    { text: 'Dashboard Notifications', link: '/foundation/dashboard-notifications' },
                    { text: 'Query Filters', link: '/foundation/query-filters' },
                    {
                        text: 'Traits',
                        collapsed: true,
                        items: [
                            { text: 'CanUploadFile', link: '/foundation/traits/can-upload-file' },
                            { text: 'RespondAsApi', link: '/foundation/traits/respond-as-api' },
                            { text: 'Taggable', link: '/foundation/traits/taggable' },
                            { text: 'UserAuditable', link: '/foundation/traits/user-auditable' },
                        ],
                    },
                ],
            },
            {
                text: 'Commands',
                collapsed: false,
                items: [
                    { text: 'Artisan Commands', link: '/commands/overview' },
                    { text: 'Scaffolding & Stubs', link: '/commands/scaffolding-and-stubs' },
                ],
            },
            {
                text: 'Packages',
                collapsed: false,
                items: [
                    {
                        text: 'Auth',
                        collapsed: true,
                        items: [
                            { text: 'Overview', link: '/packages/auth/overview' },
                            { text: 'Actions', link: '/packages/auth/actions' },
                            { text: 'Routes', link: '/packages/auth/routes' },
                            { text: 'Customization', link: '/packages/auth/customization' },
                        ],
                    },
                    {
                        text: 'Datatables',
                        collapsed: true,
                        items: [
                            { text: 'Overview', link: '/packages/datatables/overview' },
                            { text: 'Columns', link: '/packages/datatables/columns' },
                            { text: 'Filters', link: '/packages/datatables/filters' },
                            { text: 'Actions', link: '/packages/datatables/actions' },
                            { text: 'Export (PDF)', link: '/packages/datatables/export' },
                            { text: 'Frontend & Scaffolding', link: '/packages/datatables/frontend' },
                        ],
                    },
                    { text: 'Sidebar', link: '/packages/sidebar' },
                    { text: 'Toastify', link: '/packages/toastify' },
                    { text: 'Lang Extractor', link: '/packages/lang-extractor' },
                ],
            },
            {
                text: 'Frontend',
                collapsed: false,
                items: [
                    { text: 'Asset & Init System', link: '/frontend/asset-system' },
                    { text: 'Theming', link: '/frontend/theming' },
                    { text: 'Stylesheets', link: '/frontend/stylesheets' },
                    { text: 'JS Translations', link: '/frontend/translations' },
                    { text: 'Service Worker', link: '/frontend/service-worker' },
                    {
                        text: 'Redot Plugins',
                        collapsed: true,
                        items: [
                            { text: 'RedotIconPicker', link: '/frontend/plugins/redot-icon-picker' },
                            { text: 'RedotRepeater', link: '/frontend/plugins/redot-repeater' },
                            { text: 'RedotUploader', link: '/frontend/plugins/redot-uploader' },
                            { text: 'RedotValidator', link: '/frontend/plugins/redot-validator' },
                            { text: 'RedotValidatorRules', link: '/frontend/plugins/redot-validator-rules' },
                            { text: 'RedotVisibility', link: '/frontend/plugins/redot-visibility' },
                        ],
                    },
                    {
                        text: 'Initializers',
                        collapsed: true,
                        items: [
                            { text: 'Coloris', link: '/frontend/inits/coloris' },
                            { text: 'Icon Picker', link: '/frontend/inits/icon-picker' },
                            { text: 'Query Builder', link: '/frontend/inits/query-builder' },
                            { text: 'Repeater', link: '/frontend/inits/repeater' },
                            { text: 'Sortable', link: '/frontend/inits/sortable' },
                            { text: 'Tempus Dominus', link: '/frontend/inits/tempus-dominus' },
                            { text: 'TinyMCE', link: '/frontend/inits/tinymce' },
                            { text: 'Tom Select', link: '/frontend/inits/tomselect' },
                            { text: 'Turnstile', link: '/frontend/inits/turnstile' },
                            { text: 'Uploader', link: '/frontend/inits/uploader' },
                        ],
                    },
                ],
            },
            {
                text: 'Components',
                collapsed: false,
                items: [
                    { text: 'Overview', link: '/components/overview' },
                    { text: 'Alert', link: '/components/alert' },
                    { text: 'Attachments', link: '/components/attachments' },
                    { text: 'Avatar', link: '/components/avatar' },
                    { text: 'Captcha', link: '/components/captcha' },
                    { text: 'Checkboxes', link: '/components/checkboxes' },
                    { text: 'Color Picker', link: '/components/color-picker' },
                    { text: 'Countries', link: '/components/countries' },
                    { text: 'Date Picker', link: '/components/date-picker' },
                    { text: 'Empty', link: '/components/empty' },
                    { text: 'Facebook Pixel', link: '/components/facebook-pixel' },
                    { text: 'File Hint', link: '/components/file-hint' },
                    { text: 'Flag', link: '/components/flag' },
                    { text: 'Form', link: '/components/form' },
                    { text: 'Form Card', link: '/components/form-card' },
                    { text: 'Google Analytics', link: '/components/google-analytics' },
                    { text: 'Hint', link: '/components/hint' },
                    { text: 'Icon', link: '/components/icon' },
                    { text: 'Icon Picker', link: '/components/icon-picker' },
                    { text: 'Input', link: '/components/input' },
                    { text: 'Label', link: '/components/label' },
                    { text: 'Logo', link: '/components/logo' },
                    { text: 'Page Header', link: '/components/page-header' },
                    { text: 'Page Loader', link: '/components/page-loader' },
                    { text: 'Pagination', link: '/components/pagination' },
                    { text: 'Query Builder', link: '/components/query-builder' },
                    { text: 'Radios', link: '/components/radios' },
                    { text: 'Radios Colored', link: '/components/radios-colored' },
                    { text: 'Rating', link: '/components/rating' },
                    { text: 'Repeater', link: '/components/repeater' },
                    { text: 'Repeater Card', link: '/components/repeater-card' },
                    { text: 'Rich Editor', link: '/components/rich-editor' },
                    { text: 'Select', link: '/components/select' },
                    { text: 'Social Icon', link: '/components/social-icon' },
                    { text: 'Status', link: '/components/status' },
                    { text: 'Textarea', link: '/components/textarea' },
                    { text: 'Toggle', link: '/components/toggle' },
                    { text: 'Translatable', link: '/components/translatable' },
                    { text: 'Translatable Switcher', link: '/components/translatable-switcher' },
                    { text: 'Uploader', link: '/components/uploader' },
                ],
            },
            {
                text: 'Layouts & Templates',
                collapsed: false,
                items: [
                    { text: 'Layouts', link: '/layouts/overview' },
                    { text: 'Templates', link: '/layouts/templates' },
                ],
            },
        ],
    },
});
